config/routes.rb
Rails.application.routes.draw do

  # get 'assign_marks/index'
  # get 'assign_marks/new'
  resources :students
  # resources :assign_marks, :except => [:new]
  get "/assign_marks/new/:id" => "assign_marks#new", as: :new_assign_mark

  root "staffs#index"
  devise_for :users, skip: [:registration]
  resources :staffs
  get "/staffs/new_mark/:id", to: "staffs#new_mark", as: :new_mark
  post "/staffs/assign_mark/:id", to: "staffs#assign_mark", as: :staff_assign_mark
  put "/staffs/assign_edit/:id", to: "staffs#assign_edit", as: :assign_edit


  match 'staffs/:id' => 'staffs#destroy', :via => :delete, :as => :admin_destroy_user
  get "/subjects/assign/:id", to: "subjects#assign", as: :assign
  post "/subjects/assign_subject/:id", to: "subjects#assign_subject", as: :assign_subject

  resources :subjects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController

  def index
  	@users = User.where(role: "user")
  	@assigned_subjects = AssignSubject.where(user_id: current_user.id)
  	if current_user.admin?
  	  @assigned_marks = AssignMark.all
  	  @assigned_subjects = AssignSubject.all
  	  @students = Student.all
  	  @rank_lists = RankList.all.order("total DESC")
  	else
      @assigned_marks = AssignMark.where(user_id: current_user.id)
  	end
  end

  def new 
  	@user = User.new
  end

  def create
  	@user = User.new(sign_up_params)
  	if @user.save
  		flash[:notice] = "Staff was created successfully."
  		redirect_to staffs_path
  	else
  		flash[:notice] = "Staff email already exists."
  		render "new"
  	end
  end

  def new_mark
  	@assign_mark = AssignMark.new
  	@assigned_subject = AssignSubject.find_by(id: params[:id])
  end

  def assign_mark
  	@assigned_subject = AssignSubject.find_by(id: params[:id])
  	@assign_mark = AssignMark.new(assign_params)
  	@assign_mark.user_id = current_user.id
    if @assign_mark.student_id.nil?
		flash[:notice] = "Please select student id."
        render "new_mark"
  	elsif AssignMark.find_by(student_id: @assign_mark.student_id, subject_id: @assign_mark.subject_id) != nil
	    flash[:notice] = "Student ID is already taken."
        render "new_mark"
	else	    	
    	@assign_mark.save
	  	if RankList.find_by(student_id: @assign_mark.student_id) != nil
	  		@temp = RankList.find_by(student_id: @assign_mark.student_id)
	  		mark = AssignMark.where(student_id: @assign_mark.student_id).sum(:mark)
	  		@temp.update_attributes(student_id: @assign_mark.student_id, total: mark)
	  	else
	    	RankList.create(student_id: @assign_mark.student_id, total: @assign_mark.mark)
	    end
        flash[:notice] = "Mark was assigned successfully."
        redirect_to staffs_path
    end
  end

  def edit
  	@assign_mark = AssignMark.find(params[:id])
  	@subject = Subject.find_by(id: @assign_mark.subject_id)
  end

  def assign_edit
  	@assign_mark = AssignMark.find(params[:id])
    if @assign_mark.update(assign_params)
    	@assign = AssignMark.find_by(student_id: @assign_mark.student_id)
    	@temp = RankList.find_by(student_id: @assign_mark.student_id)
        mark = AssignMark.where(student_id: @assign_mark.student_id).sum(:mark)
        @temp.update_attributes(student_id: @assign_mark.student_id, total: mark)
      flash[:notice] = "Student mark was updated successfully."
      redirect_to staffs_path
    end
  end

  def destroy
  	@user = User.find(params[:id])
  	if @user.destroy
  		flash[:notice] = "Student record deleted successfully"
  		redirect_to staffs_path
  	else
  		flash[:notice] = "something error"
  		redirect_to staffs_path
  	end
  end

 private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def assign_params
    params.require(:assign_mark).permit(:mark, :subject_id, :student_id)
  end

end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_admin.html.erb
<div class="row">
    <div class="col-md-6  col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Students Rank</h3>
            </div>
            <div class="panel-body">
                <table class="table table-hover">
                    <thead>
                        <tr>
                          <th>Student Code</th>
                          <th>Student Name</th>
                          <th>Marks</th>
                          <th>Rank</th>
                        </tr>
                    </thead>
                    <tbody>
                      <% rank_list = 0 %>
                      <% total_temp = 0 %>
                        <% @rank_lists.all.each do |rank| %>
                          <tr>
                            <% student = @students.find_by(id: rank.student_id)%>
                            <td><%= student.try(:student_code) %></td>
                            <td><%= student.try(:student_name) %></td>
                            <td><%= rank.try(:total) %></td>
                            <th>
                              <% if total_temp == rank.total %>
                                <%= rank_list %></th>
                              <% else %>
                                <%= rank_list += 1%></th>
                              <% end %>
                          </tr>
                          <% total_temp = rank.try(:total) %>
                        <% end %>
                    </tbody>
                </table>

            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Staffs List</h3>
            </div>
            <div class="panel-body">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                      <% @users.each do |user| %>
                        <tr>
                            <td><%= user.try(:name) %></td>
                            <td><%= user.try(:email) %></td>
                            <td><%= link_to "<i class='fa fa-trash'></i>".html_safe, admin_destroy_user_path(user), method: :delete, data: { confirm: "Are you sure?, if delete a user and assigned subject are also deleted." } %>

                            </td>
                        </tr>
                      <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

app/views/staffs/_form.html.erb
<div class="row">
  <div class="col-md-12">
      <div class="panel panel-default">
          <div class="panel-heading">
              <h3 class="panel-title">New Staff</h3>
          </div>
          <div class="panel-body">
			<%= form_for(@user, url: staffs_path, class: "form-horizontal form-border", id: "form") do |f| %>
			  <div class="field">
				<div class="col-sm-6">
	              <label class="col-sm-6 control-label">Name</label>
	               <%= f.text_field :name, required: true, class: "form-control", placeholder: "Zuan Denish" %>
	            </div>
			  </div>

			  <div class="field">
			  	<div class="col-sm-6">
	              <label class="col-sm-6 control-label">Email</label>
			   		 <%= f.email_field :email, autofocus: true, autocomplete: "email", required: true, class: "form-control", placeholder: "zuan@example.com" %>
			   	 </div>
			  </div>

			  <div class="field">
			    <div class="col-sm-6">
	              <label class="col-sm-6 control-label">Password</label>
				    <% if @minimum_password_length %>
				    <em>(<%= @minimum_password_length %> characters minimum)</em>
				    <% end %><br />
				    <%= f.password_field :password, autocomplete: "new-password", required: true, class: "form-control", placeholder: "*********" %>
				</div>
			  </div>

			  <div class="field">
			    <div class="col-sm-6">
	              <label class="col-sm-6 control-label">Passwprd Confirm</label>
			    	<%= f.password_field :password_confirmation, autocomplete: "new-password",required: true, class: "form-control", placeholder: "*********" %>
			    </div>
			  </div>
			  <br>	
			  <div class="field">
			  	 <div class="col-sm-offset-4 col-sm-8" style="padding-top: 27px;">
                    <%= f.submit "Create Staff", class: "btn btn-primary" %>
                    <%= link_to 'Back', staffs_path, class: "btn btn-primary" %>
                  </div>
			  </div>
			<% end %>
		  </div>
	</div>
</div>

<script>
$(document).ready(function() {
    app.formValidation();
});
</script>

app/views/staffs/_teacher.html.erb
<div class="row">
   <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Assigned Subjects</h3>
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                              <th>Subject Name</th>
                              <th>Subject Code</th>
                              <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @assigned_subjects.each do |user|%>
                            <tr>
                                <% subject =  Subject.find_by(id: user.subject_id) %>
                                <td><%= subject.try(:sub_name) %></td>
                                <td><%= subject.try(:sub_code) %></td>
                                <td>
                                    <%= link_to "Assign Mark".html_safe,new_mark_path(user), class: "btn btn-info btn-sm" %>
                                    <%#= link_to "<i class='fa fa-trash fa-lg'></i>".html_safe, category, method: :delete, data: {confirm: "Are you sure delete."} %>  
                                </td>
                            </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
   <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Assigned Marks</h3>
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-hover">
                         <thead>
                            <tr>
                              <th>Subject Code</th>
                              <th>Student Code</th>
                              <th>Student Name</th>
                              <th>Marks</th>
                              <th>Action</th>
                            </tr>
                          </thead>

                          <tbody>
                            <% @assigned_marks.each do |mark| %>
                              <tr>
                                <td><%= mark.subject.try(:sub_code) %></td>
                                <td><%= mark.student.try(:student_code) %></td>
                                <td><%= mark.student.try(:student_name) %></td>
                                <td><%= mark.try(:mark)%></td>
                                <td>
                                   <%= link_to "<i class='fa fa-pencil fa-lg'></i>".html_safe, edit_staff_path(mark.id), data: {confirm: "Are sure want to edit this."} %>
                                  </td>

                              </tr>
                            <% end %>
                          </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/staffs/edit.html.erb
<div class="row">
	<div class="col-md-12">
	    <div class="panel panel-default">
	        <div class="panel-heading">
	            <h3 class="panel-title">Horizontal form</h3>
	        </div>
	        <div class="panel-body">
	        	<%= form_for(@assign_mark, url: assign_edit_path(params[:id]), method: :put, class: "form-horizontal", id: "form") do |f| %>
 	  	        	<% @subject = Subject.find_by(id: @assign_mark.subject_id)%>
	        		<div class="row">
					  <div class="col-md-4">
					  	<% student = Student.find_by(id: @assign_mark.student_id) %>
						<%= f.label :'student id', class: "col-sm-6 control-label"%>
					    <%= text_field_tag :student_code, "", value: student.student_code, disabled: true, class: "form-control"%>
					    <%= f.hidden_field :student_id %>
					  </div>
					  <div class="col-md-4">
 	  	                <%= f.label :'sub code', class: "col-sm-6 control-label"%>
						<%= f.text_field :subject_code, value: @subject.try(:sub_name), class: "form-control", disabled: true%>
	      				<%= f.hidden_field :subject_id, value: @subject.try(:id)%>
					  </div>
					  <div class="col-md-4">
						<%= f.label :'mark', class: "col-sm-6 control-label"%>
						<%= f.number_field :mark, class: "form-control", required: true, max: "100", placeholder: "100"%>
					  </div>
					</div>
					<br>
	               <div class="form-group">
                      <div class="col-sm-offset-4 col-sm-8" style="padding-top: 30px;">
                        <%= f.submit "Update Mark", class: "btn btn-primary" %>
                        <%= link_to 'Back', staffs_path, class: "btn btn-primary" %>
                      </div>
                  </div>
	            <% end %>    
	        </div>
	    </div>
	</div>
</div>

<script>
$(document).ready(function() {
    app.formValidation();
});
</script>

<style type="text/css">
	#assign_mark_student_id {
    display: block;
    width: 100%;
    height: 34px;
    padding: 6px 12px;
    font-size: 14px;
    line-height: 1.42857143;
    color: #555;
    background-color: #fff;
    background-image: none;
    border: 1px solid #ccc;
    border-radius: 4px;
    -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
    box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
    -webkit-transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
    -o-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
    transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
}
</style>

<script type="text/javascript">
	$('#new_assign_mark').valid();
</script>

app/views/staffs/index.html.erb
<% if current_user.admin? %>
  <%= render "admin" , users: @users %>
<% else %>
  <%= render "teacher" , assigned_subjects: @assigned_subjects %>
<% end %>

app/views/staffs/new.html.erb
<%= render partial: "form", locals: { user: @user } %>

app/views/staffs/new_mark.html.erb
<div class="row">
	<div class="col-md-12">
	    <div class="panel panel-default">
	        <div class="panel-heading">
	            <h3 class="panel-title">Horizontal form</h3>
	            <div class="actions pull-right">
	                <i class="fa fa-expand"></i>
	                <i class="fa fa-chevron-down"></i>
	                <i class="fa fa-times"></i>
	            </div>
	        </div>
	        <div class="panel-body">
	        	<%= form_for(AssignMark.new, url: staff_assign_mark_path, class: "form-horizontal", id: "form") do |f| %>
 	  	        	<% @subject = Subject.find_by(id: @assigned_subject.subject_id)%>
	        		<div class="row">
					  <div class="col-md-4">
						<%= f.label :'student id', class: "col-sm-6 control-label"%>
					    <%= f.collection_select :student_id, Student.all, :id, :student_code, prompt: "Select Student" %>
					  </div>
					  <div class="col-md-4">
 	  	                <%= f.label :'sub code', class: "col-sm-6 control-label"%>
						<%= f.text_field :subject_code, value: @subject.try(:sub_name), class: "form-control", disabled: true%>
	      				<%= f.hidden_field :subject_id, value: @subject.try(:id)%>
					  </div>
					  <div class="col-md-4">
						<%= f.label :'mark', class: "col-sm-6 control-label"%>
						<%= f.number_field :mark, class: "form-control", required: true, max: "100", placeholder: "100"%>
					  </div>
					</div>
					<br>
	               <div class="form-group">
                      <div class="col-sm-offset-4 col-sm-8">
                        <%= f.submit "Assign Mark", class: "btn btn-primary" %>
                        <%= link_to 'Back', staffs_path, class: "btn btn-primary" %>
                      </div>
                  </div>
	            <% end %>    
	        </div>
	    </div>
	</div>
</div>

<script>
$(document).ready(function() {
    app.formValidation();
});
</script>

<style type="text/css">
	#assign_mark_student_id {
    display: block;
    width: 100%;
    height: 34px;
    padding: 6px 12px;
    font-size: 14px;
    line-height: 1.42857143;
    color: #555;
    background-color: #fff;
    background-image: none;
    border: 1px solid #ccc;
    border-radius: 4px;
    -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
    box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
    -webkit-transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
    -o-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
    transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
}
</style>

<script type="text/javascript">
	$('#new_assign_mark').valid();
</script>