config/routes.rb
Rails.application.routes.draw do

  # get 'assign_marks/index'
  # get 'assign_marks/new'
  resources :students
  # resources :assign_marks, :except => [:new]
  get "/assign_marks/new/:id" => "assign_marks#new", as: :new_assign_mark

  root "staffs#index"
  devise_for :users, skip: [:registration]
  resources :staffs
  get "/staffs/new_mark/:id", to: "staffs#new_mark", as: :new_mark
  post "/staffs/assign_mark/:id", to: "staffs#assign_mark", as: :staff_assign_mark
  put "/staffs/assign_edit/:id", to: "staffs#assign_edit", as: :assign_edit


  match 'staffs/:id' => 'staffs#destroy', :via => :delete, :as => :admin_destroy_user
  get "/subjects/assign/:id", to: "subjects#assign", as: :assign
  post "/subjects/assign_subject/:id", to: "subjects#assign_subject", as: :assign_subject

  resources :subjects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :subject, optional: true
  has_many :assign_marks, dependent: :destroy
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authorize_admin, only: [:create, :update, :index, :edit]

  def index
    @students = Student.all
    @students = @students.paginate(page: params[:page]).order("created_at DESC").per_page(5)
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def edit
    @student = Student.find(params[:id])
  end

  def create
    @student = Student.new(student_params)
    if Student.find_by(student_code: @student.student_code) != nil
        flash[:notice] = "Student ID is already taken."
        render "new"
      else
        @student.save
        flash[:notice] = "Student was successfully created."
        redirect_to students_path
    end
  end

  def update
    @student = Student.find(params[:id])
      if @student.update(student_params)
        flash[:notice] = "Student was updated successfully."
        redirect_to students_path
      end
  end

  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def authorize_admin
      return unless !current_user.admin?
      redirect_to root_path, alert: 'Admins only!'
    end

    def student_params
      params.require(:student).permit(:student_name, :student_code)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<div class="row">
  <div class="col-md-12">
      <div class="panel panel-default">
          <div class="panel-heading">
              <h3 class="panel-title">Student From</h3>
          </div>
          <div class="panel-body">
              <%= form_with(model: @student, local: true, class: "form-horizontal form-border", id: "form") do |form| %>
                  <div class="form-group">
                      <label class="col-sm-3 control-label">Student Name</label>
                      <div class="col-sm-6">
                        <%= form.text_field :student_name, required: true, class: "form-control", placeholder: "Zuan Denish" %>
                      </div>
                  </div>
                  <div class="form-group">
                      <label class="col-sm-3 control-label">Student Code</label>
                      <div class="col-sm-6">
                        <%= form.text_field :student_code, required: true, class: "form-control", placeholder: "VM5820" %>
                      </div>
                  </div>
                  <div class="form-group">
                      <div class="col-sm-offset-4 col-sm-8">
                        <%= form.submit "Create Student", class: "btn btn-primary" %>
                        <%= link_to 'Back', students_path, class: "btn btn-primary" %>
                      </div>
                  </div>
              <% end %>
          </div>
      </div>
  </div>
</div>
<script>
$(document).ready(function() {
    app.formValidation();
});
</script>

app/views/students/edit.html.erb
<div class="row">
  <div class="col-md-12">
      <div class="panel panel-default">
          <div class="panel-heading">
              <h3 class="panel-title">Student From</h3>
          </div>
          <div class="panel-body">
              <%= form_with(model: @student, local: true, class: "form-horizontal form-border", id: "form") do |form| %>
                  <div class="form-group">
                      <label class="col-sm-3 control-label">Student Name</label>
                      <div class="col-sm-6">
                        <%= form.text_field :student_name, required: true, class: "form-control", placeholder: "Zuan Denish" %>
                      </div>
                  </div>
                  <div class="form-group">
                      <label class="col-sm-3 control-label">Student Code</label>
                      <div class="col-sm-6">
                        <%= form.text_field :student_code, class: "form-control", placeholder: "VM5820", readonly: true %>
                      </div>
                  </div>
                  <div class="form-group">
                      <div class="col-sm-offset-4 col-sm-8">
                        <%= form.submit "Create Student", class: "btn btn-primary" %>
                        <%= link_to 'Back', students_path, class: "btn btn-primary" %>
                      </div>
                  </div>
              <% end %>
          </div>
      </div>
  </div>
</div>
<script>
$(document).ready(function() {
    app.formValidation();
});
</script>

app/views/students/index.html.erb
<div class="row">
   <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Students Records</h3>
                 <div class="actions">
                        <div class="row">
                            <div class="col-md-4">
                                <%= link_to new_student_path do %>
                                <span class="btn btn-info btn-trans btn-sm"><i class="fa fa-plus"></i>New Student</span>
                                <% end %>
                            </div>
                        </div>
                  </div>
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                          <tr>
                            <th>Student name</th>
                            <th>Student code</th>
                            <th>Created At</th>
                            <th colspan="3">Actions</th>
                          </tr>
                        </thead>

                        <tbody>
                          <% @students.each do |student| %>
                            <tr>
                              <td><%= student.try(:student_name) %></td>
                              <td><%= student.try(:student_code) %></td>
                              <td><%= student.created_at.strftime(" %d-%b-%y")%></td>

                              <td>
                                <%#= link_to 'Show', student %>
                                 <%= link_to "<i class='fa fa-pencil fa-lg'></i>".html_safe, edit_student_path(student), data: {confirm: "Are sure want to edit this."} %>
                                 <%#= link_to "<i class='fa fa-trash fa-lg'></i>".html_safe,student, method: :delete, data: {confirm: "Are sure want to delete this."} %>
                                <%#= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %>
                              </td>
                            </tr>
                          <% end %>
                        </tbody>
                    </table>

                    <div class="col-md-12 text-center">
                        <%= will_paginate @students, container: false%>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/students/new.html.erb
<%= render 'form', student: @student %>

app/views/students/show.html.erb
<p>
  <strong>Student name:</strong>
  <%= @student.student_name %>
</p>

<p>
  <strong>Student code:</strong>
  <%= @student.student_code %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>