config/routes.rb
Rails.application.routes.draw do

  # get 'assign_marks/index'
  # get 'assign_marks/new'
  resources :students
  # resources :assign_marks, :except => [:new]
  get "/assign_marks/new/:id" => "assign_marks#new", as: :new_assign_mark

  root "staffs#index"
  devise_for :users, skip: [:registration]
  resources :staffs
  get "/staffs/new_mark/:id", to: "staffs#new_mark", as: :new_mark
  post "/staffs/assign_mark/:id", to: "staffs#assign_mark", as: :staff_assign_mark
  put "/staffs/assign_edit/:id", to: "staffs#assign_edit", as: :assign_edit


  match 'staffs/:id' => 'staffs#destroy', :via => :delete, :as => :admin_destroy_user
  get "/subjects/assign/:id", to: "subjects#assign", as: :assign
  post "/subjects/assign_subject/:id", to: "subjects#assign_subject", as: :assign_subject

  resources :subjects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :user, optional: true
  has_many :students, dependent: :destroy
  has_many :assign_subjects, dependent: :destroy
  has_many :assign_marks, dependent: :destroy

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :authorize_admin, only: [:create, :update, :index, :edit]

  def index
    @subjects = Subject.all
    @subjects = @subjects.paginate(page: params[:page]).order("created_at DESC").per_page(5)
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def new
    @subject = Subject.new
  end

  def edit
    @subject = Subject.find(params[:id])
  end

  def assign
    @assign_subject = AssignSubject.new
    @users = User.where.not(role: :admin)
  end

  def assign_subject
    @assign_subject = AssignSubject.new(assign_params)
    if @assign_subject.user_id.nil?
      flash[:notice] = "Can you please select a staff."
      render "assign"
    elsif AssignSubject.find_by(subject_id: @assign_subject.subject_id).present? 
      flash[:notice] = "Subject code is already assigned."
      render "assign"
    else
      @assign_subject.save
      flash[:notice] = "Subject code is was assigned successfully."
      redirect_to subjects_path
    end
  end

  def create
    @subject = Subject.new(subject_params)
    @subject.user_id = current_user.id
    if Subject.find_by(sub_code: @subject.sub_code) != nil
        flash[:notice] = "Student code is already taken."
        render "new"
      else
        @subject.save
        flash[:notice] = "Subject was successfully created."
        redirect_to subjects_path
    end
  end

  def update
    @subject = Subject.find(params[:id])
      if @subject.update(subject_params)
        @subject.save
        flash[:notice] = "Subject was successfully updated."
        redirect_to subjects_path
      end
  end

  def destroy
    @subject = Subject.find(params[:id])
    if @subject.assign_subjects.count > 0
      flash[:notice] = "Subject was associated in teachers"
      redirect_to subjects_path
    else
      @subject.delete
      flash[:notice] = "Product was deleted successfully."
      redirect_to subjects_path
    end
  end

  private
    def subject_params
      params.require(:subject).permit(:sub_name, :sub_code)
    end
    def authorize_admin
      return unless !current_user.admin?
      redirect_to root_path, alert: 'Admins only!'
    end
    def assign_params
      params.require(:assign_subject).permit(:subject_id, :user_id)
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<div class="row">
  <div class="col-md-12">
      <div class="panel panel-default">
          <div class="panel-heading">
              <h3 class="panel-title">Form Subject</h3>
          </div>
          <div class="panel-body">
              <%= form_with(model: @subject, local: true, class: "form-horizontal form-border", id: "form") do |form| %>
                  <div class="form-group">
                      <label class="col-sm-3 control-label">Subject Name</label>
                      <div class="col-sm-6">
                        <%= form.text_field :sub_name, required: true, class: "form-control", placeholder: "Ruby On Rails" %>
                      </div>
                  </div>
                  <div class="form-group">
                      <label class="col-sm-3 control-label">Subject Code</label>
                      <div class="col-sm-6">
                        <%= form.text_field :sub_code, required: true, minlength: "2", limit: "10", class: "form-control", placeholder: "ROR1122" %>
                      </div>
                  </div>
                  <div class="form-group">
                      <div class="col-sm-offset-4 col-sm-8">
                        <%= form.submit "Create Subject", class: "btn btn-primary" %>
                        <%= link_to 'Back', subjects_path, class: "btn btn-primary" %>

                      </div>
                  </div>
              <% end %>
          </div>
      </div>
  </div>
</div>

<script>
$(document).ready(function() {
    app.formValidation();
});
</script>

app/views/subjects/assign.html.erb
<div class="row">
  <div class="col-md-12">
      <div class="panel panel-default">
          <div class="panel-heading">
              <h3 class="panel-title">Assign Staff</h3>
          </div>
          <div class="panel-body">
              <%= form_for(AssignSubject.new, url: assign_subject_path, class: "form-horizontal form-border") do |f| %>
                    
                   <div class="field">
                      <div class="col-sm-6">
                          <label class="col-sm-6 control-label">Subject Code</label>
                          <% @subject = Subject.find_by(id: params[:id])%>
                          <%= f.text_field :subject, value: @subject.try(:sub_code), class: "form-control", disabled: true %>
                          <%= f.hidden_field :subject_id, value: @subject.try(:id)%>
                      </div>
                    </div>

                    <div class="field">
                      <div class="col-sm-6">
                          <label class="col-sm-6 control-label">Assign to Staff</label>
                          <% users = User.where.not(role: :admin)%>
                          <%= f.collection_select :user_id , users.all, :id, :name, prompt: "Select Staff"%>
                       </div>
                    </div>
                   <div class="field">
                  </div>
                  <div class="form-group">
                      <div class="col-sm-offset-4 col-sm-8" style="padding-top: 30px;">
                        <%= f.submit "Assign ", class: "btn btn-primary" %>
                        <%= link_to 'Back', subjects_path, class: "btn btn-primary" %>

                      </div>
                  </div>
              <% end %>
          </div>
      </div>
  </div>
</div>


<style type="text/css">
  #assign_subject_user_id {
    display: block;
    width: 100%;
    height: 34px;
    padding: 6px 12px;
    font-size: 14px;
    line-height: 1.42857143;
    color: #555;
    background-color: #fff;
    background-image: none;
    border: 1px solid #ccc;
    border-radius: 4px;
    -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
    box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
    -webkit-transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
    -o-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
    transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
}
</style>

app/views/subjects/edit.html.erb
<div class="row">
  <div class="col-md-12">
      <div class="panel panel-default">
          <div class="panel-heading">
              <h3 class="panel-title">Form Subject</h3>
          </div>
          <div class="panel-body">
              <%= form_with(model: @subject, local: true, class: "form-horizontal form-border", id: "form") do |form| %>
                  <div class="form-group">
                      <label class="col-sm-3 control-label">Subject Name</label>
                      <div class="col-sm-6">
                        <%= form.text_field :sub_name, required: true, class: "form-control", placeholder: "Ruby On Rails" %>
                      </div>
                  </div>
                  <div class="form-group">
                      <label class="col-sm-3 control-label">Subject Code</label>
                      <div class="col-sm-6">
                        <%= form.text_field :sub_code, class: "form-control", placeholder: "ROR1122", readonly: true %>
                      </div>
                  </div>
                  <div class="form-group">
                      <div class="col-sm-offset-4 col-sm-8">
                        <%= form.submit "Create Subject", class: "btn btn-primary" %>
                        <%= link_to 'Back', subjects_path, class: "btn btn-primary" %>

                      </div>
                  </div>
              <% end %>
          </div>
      </div>
  </div>
</div>

<script>
$(document).ready(function() {
    app.formValidation();
});
</script>

app/views/subjects/index.html.erb
<div class="row">
   <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">All Subjects </h3>
                 <div class="actions">
                        <div class="row">
                            <div class="col-md-4">
                                <%= link_to new_subject_path do %>
                                <span class="btn btn-info btn-trans btn-sm"><i class="fa fa-plus"></i>New Subject</span>
                                <% end %>
                            </div>
                        </div>
                  </div>
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                          <tr>
                            <th>Sub name</th>
                            <th>Sub code</th>
                            <th>Created At</th>
                            <th>Actions</th>
                          </tr>
                        </thead>

                        <tbody>
                          <% @subjects.each do |subject| %>
                            <tr>
                              <td><%= subject.try(:sub_name) %></td>
                              <td><%= subject.try(:sub_code) %></td>
                              <td><%= subject.created_at.strftime(" %d-%b-%y")%></td>
                              <td>
                                <%= link_to "<i class='fa fa-pencil fa-lg'></i>".html_safe, edit_subject_path(subject), data: {confirm: "Are sure want to edit this."} %>
                                <%= link_to "<i class='fa fa-trash fa-lg'></i>".html_safe,subject, method: :delete, data: {confirm: "Are sure want to delete this subject."} %>
                                <%= link_to "Assign Subject",assign_path(subject),class: "btn btn-info btn-sm" %>
                              </td>
                            </tr>
                          <% end %>
                        </tbody>
                    </table>

                    <div class="col-md-12 text-center">
                        <%= will_paginate @subjects, container: false%>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/subjects/new.html.erb
<%= render 'form', locals: { subject: @subject } %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sub name:</strong>
  <%= @subject.sub_name %>
</p>

<p>
  <strong>Sub code:</strong>
  <%= @subject.sub_code %>
</p>

<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>