config/routes.rb
Rails.application.routes.draw do

  # get 'assign_marks/index'
  # get 'assign_marks/new'
  resources :students
  # resources :assign_marks, :except => [:new]
  get "/assign_marks/new/:id" => "assign_marks#new", as: :new_assign_mark

  root "staffs#index"
  devise_for :users, skip: [:registration]
  resources :staffs
  get "/staffs/new_mark/:id", to: "staffs#new_mark", as: :new_mark
  post "/staffs/assign_mark/:id", to: "staffs#assign_mark", as: :staff_assign_mark
  put "/staffs/assign_edit/:id", to: "staffs#assign_edit", as: :assign_edit


  match 'staffs/:id' => 'staffs#destroy', :via => :delete, :as => :admin_destroy_user
  get "/subjects/assign/:id", to: "subjects#assign", as: :assign
  post "/subjects/assign_subject/:id", to: "subjects#assign_subject", as: :assign_subject

  resources :subjects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header id="header">
  <div class="brand">
      <a href="/staffs" class="logo">
          <i class="icon-layers"></i>
          <span>School</span> Tech</a>
  </div>
  <ul class="nav navbar-nav navbar-left">
      <li class="toggle-navigation toggle-left">
          <button class="sidebar-toggle" id="toggle-left">
              <i class="fa fa-bars"></i>
          </button>
      </li>
  </ul>
  <ul class="nav navbar-nav navbar-right">
      <li class="dropdown profile hidden-xs">
          <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
              <span class="meta">
                <i class="fa fa-user-circle-o fa-lg"></i>
              <span class="text-capitalize"><%= current_user.name%></span>
              <span class="caret"></span>
              </span>
          </a>
          <ul class="dropdown-menu animated fadeInRight" role="menu">
              <li>
                <span class="arrow top"></span>
              </li>
              <li class="divider"></li>
              <li>
                <%= link_to "" do %>
                    <span class="icon"><i class="fa fa-sign-out"></i>
                    </span>My Account</a>
                <% end %>

              </li>
              <li class="divider"></li>
              <li>
                  <%= link_to destroy_user_session_path, method: :delete do %>
                      <span class="icon"><i class="fa fa-sign-out"></i>
                      </span>Logout</a>
                  <% end %>
              </li>
          </ul>
      </li>
  </ul>
</header>

app/views/layouts/_sidebar.html.erb
<aside class="sidebar sidebar-left">
    <div class="sidebar-profile">
        <div class="avatar">
            <i class="on border-dark animated bounceIn"></i>
        </div>
        <div class="profile-body dropdown">
            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><h4>
                <span class="text-capitalize"><%= current_user.name%></span>
                <span class="caret"></span></h4></a>
            <small class="title"></small>
            <ul class="dropdown-menu animated fadeInRight" role="menu">
                <li class="divider"></li>
                <li>
                    <a href="javascript:void(0);">
                        <span class="icon"><i class="fa fa-user"></i>
                        </span>My Account</a>
                </li>
                <li class="divider"></li>
                <li>
                    <%= link_to destroy_user_session_path, method: :delete do %>
                        <span class="icon"><i class="fa fa-sign-out"></i>
                        </span>Logout</a>
                    <% end %>
                </li>
            </ul>
        </div>
    </div>
    <nav>
        <h5 class="sidebar-header">Navigation</h5>
        <ul class="nav nav-pills nav-stacked">
          <% if user_signed_in?%>
            <% if current_user.admin?%>
                <li class="active">
                    <%= link_to staffs_path do %>
                    <i class="fa fa-tachometer"></i> Dashboard
                    <% end %>
                </li>
                <li class="nav-dropdown">
                    <%= link_to subjects_path do %>
                      <i class="fa fa-list"></i> Subjects
                    <% end %>
                </li>
                <li class="nav-dropdown">
                    <%= link_to students_path do %>
                      <i class="fa fa-product-hunt"></i> Students
                    <% end %>
                </li>
                <li class="nav-dropdown">
                   <%= link_to new_staff_path do %>
                      <i class="fa  fa-line-chart"></i> New Staff
                    <% end %>
                </li>
            <% else %>
                <li class="active">
                    <%= link_to staffs_path do %>
                    <i class="fa fa-tachometer"></i> Dashboard
                    <% end %>
                </li>
            <% end %>
          <% end %>
        </ul>
    </nav>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>NeuBoard</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>SchoolTech</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section id="main-wrapper" class="theme-default">
      <% if user_signed_in? %>
        <%= render "layouts/header"%>
        <%= render "layouts/sidebar"%>
      <% end %>
        <section class="main-content-wrapper">
          <% if notice %>
            <p class="alert alert-success"><%= notice %></p>
          <% end %>
          <% if alert %>
            <p class="alert alert-danger"><%= alert %></p>
          <% end %>
          <section id="main-content" class="animated fadeInUp">
   
            <%= yield %>
          </section>
        </section>
    </section>
  </body>
</html>